---
- name: Add apt HTTPS support
  apt: name=apt-transport-https state=present

- name: Add apt HTTPS support
  apt: name=ca-certificates state=present

- name: Add docker key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present filename=docker

- name: Update apt cache if needed.
  apt: update_cache=yes upgrade=yes

- name: install deps
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - linux-image-extra-virtual
    - docker-engine
    - htop
