---
- file: path=/var/log/ufw.log owner=syslog group=adm mode=640 state=touch

- ufw: rule=allow port={{ item }} state=enabled
  with_items:
    - "{{ ssh_traffic_port }}"
  tags: ufw

- ufw: rule=allow port=22 state=enabled