---
# handlers file for ssh-logger
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: restart docker-ssh-logger
  command: docker run -d --restart=always --name "{{ docker_container_name }}" -p "{{ ssh_traffic_port }}":22 justinazoff/ssh-auth-logger:latest ssh-auth-logger